# Generated by Django 4.2 on 2023-05-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='print',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
