# Generated by Django 4.2 on 2023-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_rename_print_destination_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
